version: '3.7'

services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        logging:
            driver: local

    php:
        build:
            context: ./docker/php
            args:
                UID: 1000
                GID: 1000
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        logging:
            driver: local
